### PR TITLE
[txs] Require users to enter account address if they changed authkey

### PR DESCRIPTION
**Pull request by ea-open-source**
## Motivation
Users can change their account's authkey by using the command `txs authkey --new_key $NEW_AUTH_KEY`, however the current toolchains would not work with the new authkey. Reason being CLI requires users to enter their mnemonic and then derives authkey, keypair,  and account address from said mnemonics. But the new set of authkey/new mnomenic isn't linked with the old account address, so there is no way to get the correct account address.

**This PR requires the user to provide their mnemonic alongside with an optional old account address if they changed their account's address**

## Test Plan

None

## Related PRs

[Key rotation #65](https://github.com/OLSF/carpe/pull/65)

### CODE REVIEW

**Comment by 0o-de-lally** [comment]
Hello thanks for this PR. 
I don't think we want to be asking for user input in this module. For library type modules which are imported elsewhere (e.g. GUI) there will be no way to input data. Also I think we should follow Tell Don't Ask pattern here `https://martinfowler.com/bliki/TellDontAsk.html`.

There are two ways we should retrieve the user address:
1. From command line flags for each CLI app such as `--account`
2. Load from AppConfig using the 0L.toml

Also for future reference there is a rust library called Dialoguer.

**Comment by 0o-de-lally** [comment]
This looks correct thank you. Can you rebase this against the V6 branch?

**Comment by 0o-de-lally** [comment]
Admins, I think this can be merged. @sirouk @hemulin

**Comment by sirouk** [comment]
LGTM

**Pull request merged**
