### PR TITLE
VDF proofs for normal user accounts - fix in code and documentation

### PR DESCRIPTION
**Pull request by mortonbits**
## Motivation

With non-validator account running tower app was not possible, as errors occured when submitting the proof zero.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

Follow the steps of the updated docs:
https://github.com/mortonbits/libra/blob/submit-initial-vdf-proof/ol/documentation/node-ops/tower_mining_VDF_proofs.md

## Related Issue:

https://github.com/OLSF/libra/issues/807

### CODE REVIEW

**Comment by 0o-de-lally** [comment]
@mortonbits We're cleaning up some things in the `main` that went wrong. Can you branch again from main, and include your changes from there? Just want this to be a clean merge.

**Comment by mortonbits** [comment]
> @mortonbits We're cleaning up some things in the `main` that went wrong. Can you branch again from main, and include your changes from there? Just want this to be a clean merge.

-> I merged upstream/main again. Ok now?

**Comment by Eldrox** [comment]
When will this be merged?  @0o-de-lally

**Review by soaresa — APPROVED** [review]
Tested doc and code with my fullnode.

Just not sure if the best idea is to return Ok(-1) in case of error getting miner state at baklog.rs

**Pull request merged**
