### PR TITLE
Update start_a_full_node.md

### PR DESCRIPTION
**Pull request by ashiiix**
Just a doc update

### CODE REVIEW

**Review by mortonbits — COMMENTED** [review]
Thanks, make sense to document port 6178 needs to be accessible

**Comment by codilion** [comment]
I would suggest to remove the offline nodes too. 
Additionally, as the last step, change address for `json_rpc` in the `fullnode.node.yaml` to
 `address: 0.0.0.0:8080`

**Comment by ashiiix** [comment]
Yes I completly forgot that point, my bad.

**Comment by mortonbits** [comment]
> As the last step, we have to add the change address for `json_rpc` in the `fullnode.node.yaml` to `address: 0.0.0.0:8080`

Not sure if this is a good idea - in the past we had problems with this setup. Maybe @0o-de-lally can give some hint about this.

**Review by 0o-de-lally — APPROVED** [review]

**Pull request merged**
