### PR TITLE
#1143 Lesson 3 Homework - Replace an unwrap() with match select statement

### PR DESCRIPTION
**Pull request by The1OneID**

### CODE REVIEW

**Comment by 0xzoz** [comment]
Wow, that was quick - could you please add this in a comment in #1144 to keep track of what's been done and what hasn't. Thanks

**Review by 0xzoz — APPROVED** [review]
LGTM! Great work

**Comment by 0xzoz** [comment]
@The1OneID you will need to resolve conflicts before we can merge this.

**Comment by The1OneID** [comment]
> @The1OneID you will need to resolve conflicts before we can merge this.

Thank you. Resolved ^^

**Pull request merged**
