### PR TITLE
ISSUE#793: fix docs broken link in web monitor

### LINKED ISSUE #793: Good first issue: broken link in web monitor
## To reproduce
Run the web monitor, when one submits clicks on "i", the documentation page has to show up but  it links to create new wiki page. 

Screen Shot 2021-11-03 at 7 42 27 PM

The web app is located in ol/cli and the documentations are in ol/documentation

### PR DESCRIPTION
**Pull request by gustavoguimaraes**
## Motivation
Fixes #793.  Excited about this project.

### CODE REVIEW

**Review by hemulin — APPROVED** [review]
LGTM

**Comment by 0o-de-lally** [comment]
Thanks for this PR @gustavoguimaraes ! 
Could you make the link point to the file: https://github.com/OLSF/libra/blob/main/ol/documentation/node-ops/validators/web_monitor_account_dictionary.md

**Comment by gustavoguimaraes** [comment]
> Thanks for this PR @gustavoguimaraes ! Could you make the link point to the file: https://github.com/OLSF/libra/blob/main/ol/documentation/node-ops/validators/web_monitor_account_dictionary.md

You got it @0o-de-lally  :-)

**Review by sm86 — APPROVED** [review]
Thanks @gustavoguimaraes for your first PR on this repo!

**Pull request merged**
