### PR TITLE
Introduce new parameter to omit checking on-chain state for submission of first proof

### PR DESCRIPTION
**Pull request by intuitiveminds**
As discussed in the discord channel, it is currently not possible to submit the genesis proof for a freshly created account purely using the tower app

### CODE REVIEW

**Comment by gdoteof** [comment]
Commenting since I was following along on discord.

I don't think this is the correct way to solve this.  Right now the client is successfully reaching out the RPC server, which is returning an error, which the client then panics on.

Somewhere in that chain that specific error should not be an error, it should get unwrapped to just explicitly state that the tower doesn't yet exist.

https://github.com/OLSF/libra/blob/e142a7f2a0d483d4fda766882369ced128bf1ee8/ol/tower/src/backlog.rs#L92 

Right here I think there should be another branch of the `match`

that looks like

```rust
    match tower_state {
        Ok(Some(s)) => Ok((s.verified_tower_height, s.actual_count_proofs_in_epoch)),
        Ok(Nothing) => Ok((0, 0)),
        _ => bail!("Info: Received response but no remote state found. Exiting."),
    }
```

I am not a contributor just to be clear; this is just my opinion/perception.

**Comment by 0o-de-lally** [comment]
Thanks for this PR. I think there are a lot of good ideas here. The solution here to your problem is to make sure you have an RPC upstream to submit to. I have a related PR for fetching a seed list of upstreams: https://github.com/OLSF/libra/pull/980

That all said. This is really great Rust code! I'd like to repurpose this so that the user can submit proof #X from the command line. Which I think is generally useful. Are you up for trying that?

**Comment by gdoteof** [comment]
> Thanks for this PR. I think there are a lot of good ideas here. The solution here to your problem is to make sure you have an RPC upstream to submit to. I have a related PR for fetching a seed list of upstreams: #980

I am pretty certain this is not true @0o-de-lally (I originally said the same to @intuitiveminds ). 

If there is no tower state the upstream server itself returns: `{ code: -32000, message: "Server error: could not get tower state", data: None }`; the behavior is the same if there are no upstream nodes to connect to because the specific error is swallowed; however this behavior also happens in the case where the upstream node simply fails to find the tower state (because there is no tower yet).

**Comment by intuitiveminds** [comment]
> Thanks for this PR. I think there are a lot of good ideas here. The solution here to your problem is to make sure you have an RPC upstream to submit to. I have a related PR for fetching a seed list of upstreams: #980
> 

Both you and @gdoteof are more versed in this code, given that I just started digging in here, but I think the RPC upstream might not be the problem here as @gdoteof pointed out. It's more the way this particular scenario is handled.

> That all said. This is really great Rust code! I'd like to repurpose this so that the user can submit proof #X from the command line. Which I think is generally useful. Are you up for trying that?

Sure, I can do that. This assumes that our users are a bit versed (e.g. they at least know where to find the proofs in the filesystem etc.), otherwise we would have to provide a way to list the local proofs, show the remote tower height etc. (similar to Carpe, but just in the terminal). Do you only want this feature to submit a specific proof or all proofs starting at a specific one?

**Comment by 0o-de-lally** [comment]
Thanks I think this will be very helpful. You'll see that the files are always stored in the same place, and those settings are in the app config file (0L.toml). Looking forward :)

**Comment by 0o-de-lally** [comment]
@intuitiveminds Hi there, been a while, since thie was opened.

Is this change still valid? If so I can review it again. BTW can you also check your other PR and let me know if it's also relevant and ready for review?

**Comment by intuitiveminds** [comment]
This PR is pretty much superseded by https://github.com/OLSF/libra/pull/1001, so closing it.

**Pull request closed without merging**
