### PR TITLE
Code audit merge

### PR DESCRIPTION
**Pull request by jamesmeijers**
## Motivation

Audit of 0L move files
Audit.move
AutoPay.move
Cases.move
Debug.move
Demos.move
Epoch.move
FIFO.move
FullnodeState.move
GAS.move
Globals.move
Migrations.move
MinerState.move

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)

### CODE REVIEW

**Comment by jamesmeijers** [comment]
I think the CI failures are from earlier commits...

**Review by simsekgokhan — APPROVED** [review]

**Comment by simsekgokhan** [comment]
> I think the CI failures are from earlier commits...

Yes, just fixed them.

**Review by simsekgokhan — CHANGES_REQUESTED** [review]
Forgot to push mv and md files?

**Comment by jamesmeijers** [comment]
> Forgot to push mv and md files?

Sorry, did this yesterday, forgot to comment.

**Pull request merged**
