### PR TITLE
[Move] Infra Escrow and PledgedAccounts

### PR DESCRIPTION
**Pull request by 0o-de-lally**
PledgeAccounts
- [x] struct initialization on beneficiary project, and user accounts
- [x] deposit and pledge
- [x] beneficiary withdraw
- [x] logic for voting on dissolving/revoking pledge
- [x] use coins from accounts (not integers from scaffold)
- [x] transactional tests
  - [x] init
  - [x] deposit
  - [x] withdraw
  - [x] dissolve

Infrastructure Escrow
- [x] refactor epoch boundary
- [x] refactor validator rewards
- [x] refactor burn mechanism
- [x] VM initializes on genesis
- [x] VM withdraws
- [x] helper script for user to pledge
- [x] transactional tests
  - [x] init on genesis
  - [x] withdraw on epoch boundary

### CODE REVIEW

**Comment by nourspace** [comment]
I'm having issue building the binaries of this branch.

```
   Compiling executor-benchmark v0.1.0 (/root/libra/execution/executor-benchmark)
   Compiling state-sync-multiplexer v0.1.0 (/root/libra/state-sync/state-sync-v2/state-sync-multiplexer)
   Compiling ol v5.2.0 (/root/libra/ol/cli)
   Compiling diem-api v0.1.0 (/root/libra/api)
   Compiling txs v5.2.0 (/root/libra/ol/txs)
error[E0425]: cannot find function `encode_self_unjail_script_function` in module `transaction_builder`
    --> ol/txs/src/commands/valset_cmd.rs:39:34
     |
39   |             transaction_builder::encode_self_unjail_script_function()
     |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `encode_voucher_unjail_script_function`
     |
    ::: /root/libra/sdk/transaction-builder/src/stdlib.rs:6811:1
     |
6811 | pub fn encode_voucher_unjail_script_function(addr: AccountAddress) -> TransactionPayload {
     | ---------------------------------------------------------------------------------------- similarly named function `encode_voucher_unjail_script_function` defined here

warning: ignoring -C extra-filename flag due to -o flag

For more information about this error, try `rustc --explain E0425`.
warning: `txs` (lib) generated 1 warning
error: could not compile `txs` due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:93: bins] Error 101
The command '/bin/sh -c RUSTC_WRAPPER=sccache make bins' returned a non-zero code: 2
```

**Comment by sirouk** [comment]
Incredible 👍🏼

**Review by 0xzoz — APPROVED** [review]

**Comment by nourspace** [comment]
I wish I could review this better. I tried to build again from https://github.com/0LNetworkCommunity/libra/commit/a38a07216c013086ca66072637787a2cfa606c17 and got the same error. Not sure this is a real issue. But @sirouk and I would use a docker image to set up the testnet. As it is now, this image can't be built.

**Comment by 0o-de-lally** [comment]
> I'm having issue building the binaries of this branch.

Yeah you'll need to build stdlib again: from root: `sh ol/util/build_stdlib.sh`

cc @0xzoz

**Comment by 0o-de-lally** [comment]
@hemulin 

Start in PledgeAccounts
https://github.com/0LNetworkCommunity/libra/pull/1236/files#diff-cf584d0dbf812d6fc61acddcdf686c37bcde9d95914f15744f3b83edc62ad0f4

And then InfrastructureEscrow
https://github.com/0LNetworkCommunity/libra/pull/1236/files#diff-72e528c00ee4f636bbbca7cce49625c22feaf3210368226bd41dd0c010595186

**Comment by 0xzoz** [comment]
Closing due to changes included #1261

**Pull request closed without merging**
