### PR TITLE
[tools] Restore cmd to take version

### PR DESCRIPTION
**Pull request by 0o-de-lally**
Allow a `version` param to be passed to `ol restore` so that epoch-archive bundles with blocks other than epoch boundary can be restored from.

### CODE REVIEW

**Comment by 1b5d** [comment]
When I restore -e 169 -v 37334543 it works, but when I run full node:

2022-04-26T19:20:38.570493Z [main] WARN storage/diemdb/src/lib.rs:1053 DiemDB API returned error. {"api_name":"get_account_state_with_proof_by_version","error":"Missing state root node at version 37334543, probably pruned."}
2022-04-26T19:20:38.593678Z [main] ERROR common/crash-handler/src/lib.rs:38 details = '''panicked at '[diem-node] failed to get Diem root address account state: Missing state root node at version 37334543, probably pruned.', diem-node/src/lib.rs:181:10'''
backtrace = '''

**Comment by 1b5d** [comment]
When I run only epoch: restore -e 169

2022-04-26T19:22:58.865832Z [main] ERROR storage/backup/backup-cli/src/utils/error_notes.rs:14 Error raised, see notes. {"error":"No such file or directory (os error 2)","notes":"\"/home/abed/.0L/restore/169/transaction_37255419-.3c33/37255419-.chunk\""}
2022-04-26T19:22:58.865890Z [main] INFO storage/backup/backup-cli/src/backup_types/transaction/restore.rs:315 transaction restore started. Manifest: /home/abed/.0L/restore/169/37334543/transaction_37255419-.3c33/transaction.manifest
2022-04-26T19:22:58.866512Z [main] ERROR storage/backup/backup-cli/src/bin/db-restore.rs:60 main_impl() failed: transaction restore failed: Preheat failed: No such file or directory (os error 2)
Error: transaction restore failed: Preheat failed: No such file or directory (os error 2)

**Review by intuitiveminds — APPROVED** [review]
LGTM

**Review by ashiiix — APPROVED** [review]
lgtm

**Review by soaresa — APPROVED** [review]
LGTM

**Pull request merged**
